language: php

php:
- 5.3
- 5.4
- 5.5
- 5.6
- 7.0
- 7.1

before_script:
    - composer self-update
    - composer update --dev -o -n --ignore-platform-reqs

script:
    - php bin/console benchmap -s 1
    - php bin/console benchmap -s 10
    - php bin/console benchmap -s 100
    - php bin/console benchmap -s 1000
    - php bin/console benchmap -s 10000
    - php bin/console benchmap -s 100000
